//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HotelDBModel", "RoomTypeRoom", "RoomType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HotelService.RoomType), "Room", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HotelService.Room))]
[assembly: EdmRelationshipAttribute("HotelDBModel", "RoomRoomReservation", "Room", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HotelService.Room), "RoomReservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HotelService.RoomReservation))]
[assembly: EdmRelationshipAttribute("HotelDBModel", "GuestRoomReservation", "Guest", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HotelService.Guest), "RoomReservation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HotelService.RoomReservation))]
[assembly: EdmRelationshipAttribute("HotelDBModel", "RoomReservationPayment", "RoomReservation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HotelService.RoomReservation), "Payment", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HotelService.Payment))]

#endregion

namespace HotelService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HotelDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HotelDBEntities object using the connection string found in the 'HotelDBEntities' section of the application configuration file.
        /// </summary>
        public HotelDBEntities() : base("name=HotelDBEntities", "HotelDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HotelDBEntities object.
        /// </summary>
        public HotelDBEntities(string connectionString) : base(connectionString, "HotelDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HotelDBEntities object.
        /// </summary>
        public HotelDBEntities(EntityConnection connection) : base(connection, "HotelDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RoomType> RoomTypes
        {
            get
            {
                if ((_RoomTypes == null))
                {
                    _RoomTypes = base.CreateObjectSet<RoomType>("RoomTypes");
                }
                return _RoomTypes;
            }
        }
        private ObjectSet<RoomType> _RoomTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Room> Rooms
        {
            get
            {
                if ((_Rooms == null))
                {
                    _Rooms = base.CreateObjectSet<Room>("Rooms");
                }
                return _Rooms;
            }
        }
        private ObjectSet<Room> _Rooms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RoomReservation> RoomReservations
        {
            get
            {
                if ((_RoomReservations == null))
                {
                    _RoomReservations = base.CreateObjectSet<RoomReservation>("RoomReservations");
                }
                return _RoomReservations;
            }
        }
        private ObjectSet<RoomReservation> _RoomReservations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Guest> Guests
        {
            get
            {
                if ((_Guests == null))
                {
                    _Guests = base.CreateObjectSet<Guest>("Guests");
                }
                return _Guests;
            }
        }
        private ObjectSet<Guest> _Guests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Payment> Payments
        {
            get
            {
                if ((_Payments == null))
                {
                    _Payments = base.CreateObjectSet<Payment>("Payments");
                }
                return _Payments;
            }
        }
        private ObjectSet<Payment> _Payments;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RoomTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoomTypes(RoomType roomType)
        {
            base.AddObject("RoomTypes", roomType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rooms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRooms(Room room)
        {
            base.AddObject("Rooms", room);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RoomReservations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoomReservations(RoomReservation roomReservation)
        {
            base.AddObject("RoomReservations", roomReservation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Guests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGuests(Guest guest)
        {
            base.AddObject("Guests", guest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Payments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPayments(Payment payment)
        {
            base.AddObject("Payments", payment);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HotelDBModel", Name="Guest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Guest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Guest object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="passportNo">Initial value of the PassportNo property.</param>
        public static Guest CreateGuest(global::System.Int32 id, global::System.String name, global::System.String passportNo)
        {
            Guest guest = new Guest();
            guest.Id = id;
            guest.Name = name;
            guest.PassportNo = passportNo;
            return guest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PassportNo
        {
            get
            {
                return _PassportNo;
            }
            set
            {
                OnPassportNoChanging(value);
                ReportPropertyChanging("PassportNo");
                _PassportNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PassportNo");
                OnPassportNoChanged();
            }
        }
        private global::System.String _PassportNo;
        partial void OnPassportNoChanging(global::System.String value);
        partial void OnPassportNoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HotelDBModel", "GuestRoomReservation", "RoomReservation")]
        public EntityCollection<RoomReservation> RoomReservations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RoomReservation>("HotelDBModel.GuestRoomReservation", "RoomReservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RoomReservation>("HotelDBModel.GuestRoomReservation", "RoomReservation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HotelDBModel", Name="Payment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Payment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Payment object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="guestAccount">Initial value of the GuestAccount property.</param>
        /// <param name="totalCharge">Initial value of the TotalCharge property.</param>
        /// <param name="cardType">Initial value of the CardType property.</param>
        public static Payment CreatePayment(global::System.Int32 id, global::System.String guestAccount, global::System.String totalCharge, global::System.String cardType)
        {
            Payment payment = new Payment();
            payment.id = id;
            payment.GuestAccount = guestAccount;
            payment.TotalCharge = totalCharge;
            payment.CardType = cardType;
            return payment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GuestAccount
        {
            get
            {
                return _GuestAccount;
            }
            set
            {
                OnGuestAccountChanging(value);
                ReportPropertyChanging("GuestAccount");
                _GuestAccount = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GuestAccount");
                OnGuestAccountChanged();
            }
        }
        private global::System.String _GuestAccount;
        partial void OnGuestAccountChanging(global::System.String value);
        partial void OnGuestAccountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TotalCharge
        {
            get
            {
                return _TotalCharge;
            }
            set
            {
                OnTotalChargeChanging(value);
                ReportPropertyChanging("TotalCharge");
                _TotalCharge = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TotalCharge");
                OnTotalChargeChanged();
            }
        }
        private global::System.String _TotalCharge;
        partial void OnTotalChargeChanging(global::System.String value);
        partial void OnTotalChargeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CardType
        {
            get
            {
                return _CardType;
            }
            set
            {
                OnCardTypeChanging(value);
                ReportPropertyChanging("CardType");
                _CardType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CardType");
                OnCardTypeChanged();
            }
        }
        private global::System.String _CardType;
        partial void OnCardTypeChanging(global::System.String value);
        partial void OnCardTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HotelDBModel", "RoomReservationPayment", "RoomReservation")]
        public RoomReservation RoomReservation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RoomReservation>("HotelDBModel.RoomReservationPayment", "RoomReservation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RoomReservation>("HotelDBModel.RoomReservationPayment", "RoomReservation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RoomReservation> RoomReservationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RoomReservation>("HotelDBModel.RoomReservationPayment", "RoomReservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RoomReservation>("HotelDBModel.RoomReservationPayment", "RoomReservation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HotelDBModel", Name="Room")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Room : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Room object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="roomNo">Initial value of the RoomNo property.</param>
        public static Room CreateRoom(global::System.Int32 id, global::System.String roomNo)
        {
            Room room = new Room();
            room.Id = id;
            room.RoomNo = roomNo;
            return room;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoomNo
        {
            get
            {
                return _RoomNo;
            }
            set
            {
                OnRoomNoChanging(value);
                ReportPropertyChanging("RoomNo");
                _RoomNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoomNo");
                OnRoomNoChanged();
            }
        }
        private global::System.String _RoomNo;
        partial void OnRoomNoChanging(global::System.String value);
        partial void OnRoomNoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HotelDBModel", "RoomTypeRoom", "RoomType")]
        public RoomType RoomType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RoomType>("HotelDBModel.RoomTypeRoom", "RoomType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RoomType>("HotelDBModel.RoomTypeRoom", "RoomType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RoomType> RoomTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RoomType>("HotelDBModel.RoomTypeRoom", "RoomType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RoomType>("HotelDBModel.RoomTypeRoom", "RoomType", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HotelDBModel", "RoomRoomReservation", "RoomReservation")]
        public EntityCollection<RoomReservation> RoomReservations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RoomReservation>("HotelDBModel.RoomRoomReservation", "RoomReservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RoomReservation>("HotelDBModel.RoomRoomReservation", "RoomReservation", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HotelDBModel", Name="RoomReservation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RoomReservation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RoomReservation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        /// <param name="noOfGuest">Initial value of the NoOfGuest property.</param>
        public static RoomReservation CreateRoomReservation(global::System.Int32 id, global::System.DateTime startDate, global::System.DateTime endDate, global::System.Int32 noOfGuest)
        {
            RoomReservation roomReservation = new RoomReservation();
            roomReservation.Id = id;
            roomReservation.StartDate = startDate;
            roomReservation.EndDate = endDate;
            roomReservation.NoOfGuest = noOfGuest;
            return roomReservation;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NoOfGuest
        {
            get
            {
                return _NoOfGuest;
            }
            set
            {
                OnNoOfGuestChanging(value);
                ReportPropertyChanging("NoOfGuest");
                _NoOfGuest = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NoOfGuest");
                OnNoOfGuestChanged();
            }
        }
        private global::System.Int32 _NoOfGuest;
        partial void OnNoOfGuestChanging(global::System.Int32 value);
        partial void OnNoOfGuestChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HotelDBModel", "RoomRoomReservation", "Room")]
        public Room Room
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Room>("HotelDBModel.RoomRoomReservation", "Room").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Room>("HotelDBModel.RoomRoomReservation", "Room").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Room> RoomReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Room>("HotelDBModel.RoomRoomReservation", "Room");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Room>("HotelDBModel.RoomRoomReservation", "Room", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HotelDBModel", "GuestRoomReservation", "Guest")]
        public Guest Guest
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Guest>("HotelDBModel.GuestRoomReservation", "Guest").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Guest>("HotelDBModel.GuestRoomReservation", "Guest").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Guest> GuestReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Guest>("HotelDBModel.GuestRoomReservation", "Guest");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Guest>("HotelDBModel.GuestRoomReservation", "Guest", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HotelDBModel", "RoomReservationPayment", "Payment")]
        public Payment Payment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Payment>("HotelDBModel.RoomReservationPayment", "Payment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Payment>("HotelDBModel.RoomReservationPayment", "Payment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Payment> PaymentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Payment>("HotelDBModel.RoomReservationPayment", "Payment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Payment>("HotelDBModel.RoomReservationPayment", "Payment", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HotelDBModel", Name="RoomType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RoomType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RoomType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="capacity">Initial value of the Capacity property.</param>
        /// <param name="dailyCharge">Initial value of the DailyCharge property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static RoomType CreateRoomType(global::System.Int32 id, global::System.String capacity, global::System.Int32 dailyCharge, global::System.String name)
        {
            RoomType roomType = new RoomType();
            roomType.Id = id;
            roomType.Capacity = capacity;
            roomType.DailyCharge = dailyCharge;
            roomType.Name = name;
            return roomType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Capacity
        {
            get
            {
                return _Capacity;
            }
            set
            {
                OnCapacityChanging(value);
                ReportPropertyChanging("Capacity");
                _Capacity = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Capacity");
                OnCapacityChanged();
            }
        }
        private global::System.String _Capacity;
        partial void OnCapacityChanging(global::System.String value);
        partial void OnCapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DailyCharge
        {
            get
            {
                return _DailyCharge;
            }
            set
            {
                OnDailyChargeChanging(value);
                ReportPropertyChanging("DailyCharge");
                _DailyCharge = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DailyCharge");
                OnDailyChargeChanged();
            }
        }
        private global::System.Int32 _DailyCharge;
        partial void OnDailyChargeChanging(global::System.Int32 value);
        partial void OnDailyChargeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HotelDBModel", "RoomTypeRoom", "Room")]
        public EntityCollection<Room> Rooms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Room>("HotelDBModel.RoomTypeRoom", "Room");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Room>("HotelDBModel.RoomTypeRoom", "Room", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
