//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IHotelDataInfoUpdate")]
    public interface IHotelDataInfoUpdate {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Action="http://tempuri.org/IHotelDataInfoUpdate/checkRoomAvailability", ReplyAction="http://tempuri.org/IHotelDataInfoUpdate/checkRoomAvailabilityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IHotelDataInfoUpdate/checkRoomAvailabilityExceptionFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool checkRoomAvailability(string roomNo, string startDateStr, int duration);
        
        // CODEGEN: Generating message contract since message http://tempuri.org/IHotelDataInfoUpdate/makeRoomReservation requires protection.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelDataInfoUpdate/makeRoomReservation", ReplyAction="http://tempuri.org/IHotelDataInfoUpdate/makeRoomReservationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IHotelDataInfoUpdate/makeRoomReservationExceptionFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        ConsoleApplication1.ServiceReference2.ReservationResponse makeRoomReservation(ConsoleApplication1.ServiceReference2.ReservationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReservationRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true, ProtectionLevel=System.Net.Security.ProtectionLevel.None)]
    public partial class ReservationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign)]
        public string CardType;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign)]
        public string GuestAccount;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign)]
        public string GuestName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign)]
        public string GuestPassport;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.None, Order=0)]
        public int Duration;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.None, Order=1)]
        public int NumOfGuest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.None, Order=2)]
        public string RoomNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.None, Order=3)]
        public string StartDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.None, Order=4)]
        public string TotalCharge;
        
        public ReservationRequest() {
        }
        
        public ReservationRequest(string CardType, string GuestAccount, string GuestName, string GuestPassport, int Duration, int NumOfGuest, string RoomNo, string StartDate, string TotalCharge) {
            this.CardType = CardType;
            this.GuestAccount = GuestAccount;
            this.GuestName = GuestName;
            this.GuestPassport = GuestPassport;
            this.Duration = Duration;
            this.NumOfGuest = NumOfGuest;
            this.RoomNo = RoomNo;
            this.StartDate = StartDate;
            this.TotalCharge = TotalCharge;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReservationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true, ProtectionLevel=System.Net.Security.ProtectionLevel.None)]
    public partial class ReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.None, Order=0)]
        public string responseCode;
        
        public ReservationResponse() {
        }
        
        public ReservationResponse(string responseCode) {
            this.responseCode = responseCode;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelDataInfoUpdateChannel : ConsoleApplication1.ServiceReference2.IHotelDataInfoUpdate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelDataInfoUpdateClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference2.IHotelDataInfoUpdate>, ConsoleApplication1.ServiceReference2.IHotelDataInfoUpdate {
        
        public HotelDataInfoUpdateClient() {
        }
        
        public HotelDataInfoUpdateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelDataInfoUpdateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelDataInfoUpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelDataInfoUpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool checkRoomAvailability(string roomNo, string startDateStr, int duration) {
            return base.Channel.checkRoomAvailability(roomNo, startDateStr, duration);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference2.ReservationResponse ConsoleApplication1.ServiceReference2.IHotelDataInfoUpdate.makeRoomReservation(ConsoleApplication1.ServiceReference2.ReservationRequest request) {
            return base.Channel.makeRoomReservation(request);
        }
        
        public string makeRoomReservation(string CardType, string GuestAccount, string GuestName, string GuestPassport, int Duration, int NumOfGuest, string RoomNo, string StartDate, string TotalCharge) {
            ConsoleApplication1.ServiceReference2.ReservationRequest inValue = new ConsoleApplication1.ServiceReference2.ReservationRequest();
            inValue.CardType = CardType;
            inValue.GuestAccount = GuestAccount;
            inValue.GuestName = GuestName;
            inValue.GuestPassport = GuestPassport;
            inValue.Duration = Duration;
            inValue.NumOfGuest = NumOfGuest;
            inValue.RoomNo = RoomNo;
            inValue.StartDate = StartDate;
            inValue.TotalCharge = TotalCharge;
            ConsoleApplication1.ServiceReference2.ReservationResponse retVal = ((ConsoleApplication1.ServiceReference2.IHotelDataInfoUpdate)(this)).makeRoomReservation(inValue);
            return retVal.responseCode;
        }
    }
}
