//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TA.Window.HService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomInfo", Namespace="http://schemas.datacontract.org/2004/07/DataInfo")]
    [System.SerializableAttribute()]
    public partial class RoomInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string capacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dailyChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roomNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roomTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string capacity {
            get {
                return this.capacityField;
            }
            set {
                if ((object.ReferenceEquals(this.capacityField, value) != true)) {
                    this.capacityField = value;
                    this.RaisePropertyChanged("capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dailyCharge {
            get {
                return this.dailyChargeField;
            }
            set {
                if ((object.ReferenceEquals(this.dailyChargeField, value) != true)) {
                    this.dailyChargeField = value;
                    this.RaisePropertyChanged("dailyCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string roomNo {
            get {
                return this.roomNoField;
            }
            set {
                if ((object.ReferenceEquals(this.roomNoField, value) != true)) {
                    this.roomNoField = value;
                    this.RaisePropertyChanged("roomNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string roomType {
            get {
                return this.roomTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.roomTypeField, value) != true)) {
                    this.roomTypeField = value;
                    this.RaisePropertyChanged("roomType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HService.IHotelInfoEnquiryService")]
    public interface IHotelInfoEnquiryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelInfoEnquiryService/getAllRoomInfos", ReplyAction="http://tempuri.org/IHotelInfoEnquiryService/getAllRoomInfosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IHotelInfoEnquiryService/getAllRoomInfosExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        TA.Window.HService.RoomInfo[] getAllRoomInfos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelInfoEnquiryService/checkRoomAvailability", ReplyAction="http://tempuri.org/IHotelInfoEnquiryService/checkRoomAvailabilityResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IHotelInfoEnquiryService/checkRoomAvailabilityExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool checkRoomAvailability(string roomNo, string startDateStr, int duration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelInfoEnquiryServiceChannel : TA.Window.HService.IHotelInfoEnquiryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelInfoEnquiryServiceClient : System.ServiceModel.ClientBase<TA.Window.HService.IHotelInfoEnquiryService>, TA.Window.HService.IHotelInfoEnquiryService {
        
        public HotelInfoEnquiryServiceClient() {
        }
        
        public HotelInfoEnquiryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelInfoEnquiryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelInfoEnquiryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelInfoEnquiryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TA.Window.HService.RoomInfo[] getAllRoomInfos() {
            return base.Channel.getAllRoomInfos();
        }
        
        public bool checkRoomAvailability(string roomNo, string startDateStr, int duration) {
            return base.Channel.checkRoomAvailability(roomNo, startDateStr, duration);
        }
    }
}
